generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ArAsteriskAccount
    theme:            default
 
    fields:
      name:                  { name: Name, help: "A user readable name for the VoIP account. This name is used also inside call report in order to identify the internal telephone number of the call." }
      account_code:          { name: Asterisk Code, help: "A unique code used from the Asterisk server to identify this VoIP account. The code is inserted from the Asterisk server in the accountcode field of the CDR table." }
      ar_office:             { name: Customer Office   }
      ar_office_id:          { name: Customer Office   }
      mycustomeroffice:      { name: Customer Office   }
      displaycustomeroffice: { name: Office/Building   }
      is_active:             { name: Is Active, help: "The VoIP account is still in use. " }

    list:
      title: Asterisk VoIP Accounts
      
      fields:
        filter_on_party: { name: Customer Office, filter_criteria_disabled: true }

      display: [=_displaycustomeroffice, name, account_code, is_active]
      filters: [name, _filter_on_party, account_code, is_active]
      
    edit:
      title: Asterisk VoIP Account

      display: [_mycustomeroffice, name, account_code, is_active]