<?php

require 'generator_header.php';

?>

  /**************************************************************
   !!!                                                        !!!
   !!! WARNING: This file is automatic generated.             !!!
   !!!                                                        !!!
   !!! In order to modify this file change the content of     !!!
   !!!                                                        !!!
   !!!    /module_template/call_report_template               !!!
   !!!                                                        !!!
   !!! and execute                                            !!!
   !!!                                                        !!!
   !!!    sh generate_modules.sh                              !!! 
   !!!                                                        !!!
   **************************************************************/

all:
  is_secure: on
<?php 
if ($generateForAdmin) { 
  echo "  credentials: admin\n"; 
} else if ($generateForOffice) {
  echo "  credentials: office\n"; 
} else if ($generateForCustomer) {
  echo "  credentials: party\n"; 
} else {
  echo "  credentials: admin\n"; 
}
?>

