generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Cdr
    theme:            default

    list:
      title: Unprocessed Calls

      actions: []
      sort: [calldate, desc]

    edit:
      title: CDR can not be modified
      display: []
      actions: []

