all:
  propel:
    class:        sfPropelDatabase
    param:
      phptype:    mysql
      host:       localhost

      database:   asterisell3
      username:   asterisellfree
      password:   free
      encoding:   utf8
