generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Cdr
    theme:            default

    list:
      title: Ignored Calls

      sort: [calldate, desc]
      actions: []

    edit:
      title: CDR can not be modified
      display: []
      actions: []

