generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ArOffice
    theme:            default

    fields:
      ar_party_id:      { name: Owner Customer      }
      ar_party:         { name: Owner Customer      }
      name:             { name: Name        }
      description:      { name: Description }
      ar_rate_category_id: { name: Price Category, help: "Leave empty if it is the same price category of the owner customer. " }

    list:
      title: Customer Offices

      display: [=ar_party, name, description]
      filters: [ar_party_id, name]

    edit:
      title: Customer Offices

      display: [=ar_party_id, name, description, ar_rate_category_id]

